### ISSUE TITLE
Jira Cloud smart link support

### ISSUE THREAD

**Issue by shapel** [tarleb/jira-wiki-markup#11]
Hi
It would be great if the library supports Jira Cloud smart link format like: `[https://jira/browse/SHAP-773|https://jira/browse/SHAP-773|smart-link]` where the postfix could be:  `smart-link` , `smart-card`.

**Comment by tarleb** [comment]
Is there documentation for this feature that I could take a look at?

**Comment by shapel** [comment]
I managed to find out only an announcement (no dev specification)
https://community.atlassian.com/t5/Confluence-articles/Smart-Links-a-richer-way-to-hyperlink/ba-p/1412786

**Comment by tarleb** [comment]
Thanks, interesting feature! Can you help me to reverse engineer the syntax here? Here's what I hope would be sufficient to add this effectively.

- Why must the URL be given twice, is there a difference for what each is used?
- Can URLs contain spaces or non-ASCII characters?
- Does it work for anchor links like `#crossreference`?
- Anything else that makes these links special?

**Comment by shapel** [comment]
As far as I see 
* it's a usual link to an external resource with the title (https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=links) + postfix described how this link should be shown (`smart-link` , `smart-card`). So I suppose the same restrictions about characters for title/URL applied to them
* it doesn't work for anchor links like `#crossreference`

**Comment by tarleb** [comment]
OK, I think I can work with that. Let's see if we can squeeze this in before pandoc 2.14 is released.

**Comment by tarleb** [comment]
I found an article about dropbox integration. Are those using the same syntax?
