### ISSUE TITLE
Repo still active?

### ISSUE THREAD

**Issue by anxgstadler** [tarleb/jira-wiki-markup#19]
Hi!

Just wanted to ask if this repository is still active.
I've been forwarded to this place from the general pandoc repository with my Jira issues, but this project seems to be abandoned since May 2021?

Kind regards,
Günther

**Comment by tarleb** [comment]
Yikes, I didn't realize it's been almost a year already.

"Active" depends on the definition used: does it mean that the repo is checked regularly, and any PR would be reviewed and merged if possible? Then yes, it's active. Is it currently my priority, or do I have resources to fix the bugs? Unfortunately not, no.

I'll get back to it and fix bugs myself again, but it might a little while. All help is most welcome.
