### ISSUE TITLE
Missed {panel} in printed output

### ISSUE THREAD

**Issue by shapel** [tarleb/jira-wiki-markup#2]
Hello Albert.
First of all thx for the great lib ;)

Look like there is some issue with handling `{panel}` without title (`{panel}` with a title at least survived during converting).

Below you can find examples of described behavior

Input:
```
{panel}
Some text
{panel}

{panel:title=My Title}
Some text
{panel}
```

Action
`pandoc -f jira -t json test.md | pandoc -f json -t jira`

Output:
```
Some text

{panel}
Some text
{panel}
```

Expected that output would be the same as the input.

**Comment by tarleb** [comment]
This makes sense. We'll need to avoid panel nesting, which wouldn't give the desired result.

This will need fixing in pandoc.
