### ISSUE TITLE
Can `{noformat}` be improved?

### ISSUE THREAD

**Issue by shapel** [tarleb/jira-wiki-markup#4]
Hello 
First of all thx for the great lib ;)

Look like there is some issue with handling {noformat} (described in https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=advanced).

Below you can find examples of described behavior

Input:
```
{noformat}
preformatted piece of text
 so *no* further _formatting_ is done here
{noformat}
```

Action:
`pandoc -f jira -t json test.md | pandoc -f json -t jira`

Output:
```
{code:java}
preformatted piece of text
 so *no* further _formatting_ is done here

{code}
```
Expected that output would be the same as the input.

**Comment by shapel** [comment]
Hello
Looks like I found the case with wrong behavior for `{noformat}`:

Command `echo "{noformat}test{noformat}\n" | pandoc -f jira -t json | jq` produce 
```
{
  "pandoc-api-version": [
    1,
    22
  ],
  "meta": {},
  "blocks": []
}
```
But if we add \n after {noformat} tag than it will parsed correctly
`echo "{noformat}\ntest{noformat}\n" | pandoc -f jira -t json | jq`
```
{
  "pandoc-api-version": [
    1,
    22
  ],
  "meta": {},
  "blocks": [
    {
      "t": "CodeBlock",
      "c": [
        [
          "",
          [],
          []
        ],
        "test"
      ]
    }
  ]
}
```

**Comment by tarleb** [comment]
Argh. Please open a new issue, so we don't lose track of this
