### ISSUE TITLE
Issues with {quote}

### ISSUE THREAD

**Issue by shapel** [tarleb/jira-wiki-markup#5]
Hello.
First of all thx for the great lib ;)

Look like there is some issue with handling `{quote}` (described in https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=texteffects).

Below you can find examples of described behavior

Input:
```
{quote}
    here is quotable
 content to be quoted
{quote}
```

Action
`pandoc -f jira -t json test.md | pandoc -f json -t jira`

Output:
```
bq.  here is quotable
content to be quoted
```

Expected that output would be the same as the input.

**Comment by tarleb** [comment]
Thanks for all these excellent reports. I've fixed one and will have a
look at the remaining issues later.

Cheers!

**Comment by shapel** [comment]
Hello @tarleb 
Do you have any updates/plans about these issues?

**Comment by tarleb** [comment]
No, but it's on my list.

**Comment by tarleb** [comment]
Should be good now and will be included in the next pandoc nightly build. Let me know if something is still amiss.
