### ISSUE TITLE
Empty AST for `{noformat}` without \n after tag

### ISSUE THREAD

**Issue by shapel** [tarleb/jira-wiki-markup#7]
Hello
Looks like I found the case with wrong behavior for `{noformat}`:

Command `echo "{noformat}test{noformat}\n" | pandoc -f jira -t json | jq` produces 
```
{
  "pandoc-api-version": [
    1,
    22
  ],
  "meta": {},
  "blocks": []
}
```
But if we add \n after {noformat} tag than it will parsed correctly
`echo "{noformat}\ntest{noformat}\n" | pandoc -f jira -t json | jq`
```
{
  "pandoc-api-version": [
    1,
    22
  ],
  "meta": {},
  "blocks": [
    {
      "t": "CodeBlock",
      "c": [
        [
          "",
          [],
          []
        ],
        "test"
      ]
    }
  ]
}
```

**Comment by shapel** [comment]
Hi
Sorry for missing some other tags related to his issue like `code`, `panel`...
Should I submit a new issue or this issue should be reopened?

**Comment by tarleb** [comment]
Ah, I missed those, too. A new issue would be best.
